#!/usr/bin/env bash
# Dump per-partition QoS limits using scontrol only (no sacctmgr).
#
# Run this on each cluster's login/compute node and merge the result into
# partitions.yaml: each output entry's `qos:` map replaces the entry's
# existing `qos:` field for the matching `partition_name`.
#
# - Every QoS allowed on a partition (partition QOSList + MinQOS) gets a
#   key named after the QoS, holding its full set of limits.
# - The QoS that applies when a job requests none (the cluster default,
#   Default=YES, else the built-in "normal") is always reported under
#   the key `default` - so partitions without any non-default QoS just
#   carry a `default:` block.
# - "Unlimited" (0, empty TRES, 0-00:00:00 walltime) is emitted as null.
#
# Usage:
#   ./qos_limits.sh              # YAML to stdout
#   ./qos_limits.sh out.yaml     # YAML to file

set -euo pipefail

out="${1:-/dev/stdout}"

qos_raw="$(scontrol show qos)"
part_raw="$(scontrol show partitions)"

{
    printf '# QoS limits per partition.\n'
    printf '# Generated by qos_limits.sh on %s at %s (scontrol show qos / partitions).\n' \
        "$(hostname 2>/dev/null || echo unknown)" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    awk '
        function getkv(line, key,    pat, rest) {
            pat = key "="
            if (!match(line, pat "[^ ]*"))
                return ""
            rest = substr(line, RSTART, RLENGTH)
            sub(/^[^=]*=/, "", rest)
            return rest
        }

        function qget(q, field,    k) {
            k = q SUBSEP field
            if (k in rec)
                return rec[k]
            return ""
        }

        # Emit a TRES list ("cpu=100,memory=1G") as a nested map, or null.
        function emit_tres(key, ind, q, field,    v, n, a, i, eq, k, val) {
            v = qget(q, field)
            if (v == "") {
                printf "%s%s: null\n", ind, key
                return
            }
            n = split(v, a, ",")
            for (i = 1; i <= n; i++) {
                if (a[i] != "")
                    break
            }
            if (i > n) {
                printf "%s%s: null\n", ind, key
                return
            }
            printf "%s%s:\n", ind, key
            for (i = 1; i <= n; i++) {
                if (a[i] == "")
                    continue
                eq = index(a[i], "=")
                k = substr(a[i], 1, eq - 1)
                val = substr(a[i], eq + 1)
                printf "%s  %s: %s\n", ind, k, val
            }
        }

        # Emit a numeric limit; 0 (unlimited) becomes null.
        function emit_num(key, ind, q, field,    v) {
            v = qget(q, field)
            if (v + 0 == 0)
                printf "%s%s: null\n", ind, key
            else
                printf "%s%s: %d\n", ind, key, v
        }

        function emit_wall(key, ind, q, field,    v) {
            v = qget(q, field)
            if (v == "" || v == "0-00:00:00")
                printf "%s%s: null\n", ind, key
            else
                printf "%s%s: %s\n", ind, key, v
        }

        function emit_qos_body(q, ind) {
            emit_tres("grp_tres",            ind, q, "GrpTRES")
            emit_tres("grp_tres_mins",       ind, q, "GrpTRESMins")
            emit_tres("max_tres",            ind, q, "MaxTRES")
            emit_tres("max_tres_mins",       ind, q, "MaxTRESMins")
            emit_tres("max_tres_per_job",    ind, q, "MaxTRESPerJob")
            emit_tres("max_tres_per_node",   ind, q, "MaxTRESPerNode")
            emit_tres("max_tres_per_user",   ind, q, "MaxTRESPerUser")
            emit_wall("max_wall",            ind, q, "MaxWall")
            emit_num("max_cpus_per_node",    ind, q, "MaxCPUsNode")
            emit_num("max_mem_per_cpu",      ind, q, "MaxMemPerCPU")
            emit_num("max_mem_per_node",     ind, q, "MaxMemNode")
            emit_num("max_nodes",            ind, q, "MaxNodes")
            emit_num("min_nodes",            ind, q, "MinNodes")
            emit_num("max_jobs",             ind, q, "MaxJobs")
            emit_num("max_submit",           ind, q, "MaxSubmit")
            emit_num("priority",             ind, q, "Priority")
        }

        function emit_qos_entry(key, q,    ind) {
            ind = "        "
            if (!(q in known)) {
                printf "      %s: null  # QoS not found in scontrol show qos\n", key
                return
            }
            printf "      %s:\n", key
            emit_qos_body(q, ind)
        }

        BEGIN {
            defqos = ""
            print "partitions:"
        }

        # First input: `scontrol show qos` (one "key=value" line per field,
        # records starting with QOSName=).
        NR == FNR {
            if ($0 ~ /^QOSName=/) {
                cur = $0
                sub(/^QOSName=/, "", cur)
                known[cur] = 1
            } else if ($0 ~ /=/ && cur != "") {
                eq = index($0, "=")
                k = substr($0, 1, eq - 1)
                v = substr($0, eq + 1)
                rec[cur, k] = v
                if (k == "Default" && v == "1")
                    defqos = cur
            }
            next
        }

        # Second input: `scontrol show partitions` (one "key=value ..." line
        # per partition).
        {
            if (!match($0, /PartitionName=/))
                next
            pn = getkv($0, "PartitionName")
            qs = getkv($0, "QOSList")
            mq = getkv($0, "MinQOS")
            if (qs == "(null)")
                qs = ""
            if (mq == "(null)")
                mq = ""

            # Collect the QoS applicable to this partition, in order:
            # QOSList first, then MinQOS (deduplicated).
            cnt = 0
            split("", seen)
            split("", list)
            n = split(qs, arr, ",")
            for (i = 1; i <= n; i++) {
                if (arr[i] == "" || (arr[i] in seen))
                    continue
                seen[arr[i]] = 1
                list[++cnt] = arr[i]
            }
            if (mq != "" && !(mq in seen))
                list[++cnt] = mq

            if (defqos == "")
                defqos = "normal"

            printf "  - partition_name: %s\n", pn
            print  "    qos:"
            emit_qos_entry("default", defqos)
            for (i = 1; i <= cnt; i++) {
                if (list[i] == defqos)
                    continue
                emit_qos_entry(list[i], list[i])
            }
        }
    ' <(printf '%s\n' "$qos_raw") <(printf '%s\n' "$part_raw")
} > "$out"
